package com.oracle.xianshop.model.javabean;

import java.io.Serializable;

/**
 * 商品对比�? 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Compares implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 对比表id. */
	private Integer compareid;

	/** 商品编号. */
	private Integer goodsid;

	/**
	 * 僐儞僗僩儔僋�?.
	 */
	public Compares() {
	}

	/**
	 * 对比表id 傪愝掕偟傑偡.
	 * 
	 * @param compareid
	 *            对比表id
	 */
	public void setCompareid(Integer compareid) {
		this.compareid = compareid;
	}

	/**
	 * 对比表id 傪庢摼偟傑偡.
	 * 
	 * @return 对比表id
	 */
	public Integer getCompareid() {
		return this.compareid;
	}

	/**
	 * 商品编号 傪愝掕偟傑偡.
	 * 
	 * @param goodsid
	 *            商品编号
	 */
	public void setGoodsid(Integer goodsid) {
		this.goodsid = goodsid;
	}

	/**
	 * 商品编号 傪庢摼偟傑偡.
	 * 
	 * @return 商品编号
	 */
	public Integer getGoodsid() {
		return this.goodsid;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((compareid == null) ? 0 : compareid.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Compares other = (Compares) obj;
		if (compareid == null) {
			if (other.compareid != null) {
				return false;
			}
		} else if (!compareid.equals(other.compareid)) {
			return false;
		}

		return true;
	}

}
