package com.oracle.xianshop.model.javabean;

import java.io.Serializable;

/**
 * 商品�? 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Goods implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 商品编号. */
	private Integer goodsid;

	/** 商品名称. */
	private String goodsname;

	/** 商品类型. */
	private String goodstype;

	/** 商品价格. */
	private Double goodsprice;

	/** 商品数量. */
	private Integer goodsnumber;

	/** 商品图片. */
	private String goodspic;

	/**
	 * 僐儞僗僩儔僋�?.
	 */
	private int iscollect=0;
	public Goods() {
	}

	/**
	 * 商品编号 傪愝掕偟傑偡.
	 * 
	 * @param goodsid
	 *            商品编号
	 */
	public void setGoodsid(Integer goodsid) {
		this.goodsid = goodsid;
	}

	/**
	 * 商品编号 傪庢摼偟傑偡.
	 * 
	 * @return 商品编号
	 */
	public Integer getGoodsid() {
		return this.goodsid;
	}

	/**
	 * 商品名称 傪愝掕偟傑偡.
	 * 
	 * @param goodsname
	 *            商品名称
	 */
	public void setGoodsname(String goodsname) {
		this.goodsname = goodsname;
	}

	/**
	 * 商品名称 傪庢摼偟傑偡.
	 * 
	 * @return 商品名称
	 */
	public String getGoodsname() {
		return this.goodsname;
	}

	/**
	 * 商品类型 傪愝掕偟傑偡.
	 * 
	 * @param goodstype
	 *            商品类型
	 */
	public void setGoodstype(String goodstype) {
		this.goodstype = goodstype;
	}

	/**
	 * 商品类型 傪庢摼偟傑偡.
	 * 
	 * @return 商品类型
	 */
	public String getGoodstype() {
		return this.goodstype;
	}

	/**
	 * 商品价格 傪愝掕偟傑偡.
	 * 
	 * @param goodsprice
	 *            商品价格
	 */
	public void setGoodsprice(Double goodsprice) {
		this.goodsprice = goodsprice;
	}

	/**
	 * 商品价格 傪庢摼偟傑偡.
	 * 
	 * @return 商品价格
	 */
	public Double getGoodsprice() {
		return this.goodsprice;
	}

	/**
	 * 商品数量 傪愝掕偟傑偡.
	 * 
	 * @param goodsnumber
	 *            商品数量
	 */
	public void setGoodsnumber(Integer goodsnumber) {
		this.goodsnumber = goodsnumber;
	}

	/**
	 * 商品数量 傪庢摼偟傑偡.
	 * 
	 * @return 商品数量
	 */
	public Integer getGoodsnumber() {
		return this.goodsnumber;
	}

	/**
	 * 商品图片 傪愝掕偟傑偡.
	 * 
	 * @param goodspic
	 *            商品图片
	 */
	public void setGoodspic(String goodspic) {
		this.goodspic = goodspic;
	}

	/**
	 * 商品图片 傪庢摼偟傑偡.
	 * 
	 * @return 商品图片
	 */
	public String getGoodspic() {
		return this.goodspic;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((goodsid == null) ? 0 : goodsid.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Goods other = (Goods) obj;
		if (goodsid == null) {
			if (other.goodsid != null) {
				return false;
			}
		} else if (!goodsid.equals(other.goodsid)) {
			return false;
		}

		return true;
	}

	@Override
	public String toString() {
		return "Goods [goodsid=" + goodsid + ", goodsname=" + goodsname
				+ ", goodstype=" + goodstype + ", goodsprice=" + goodsprice
				+ ", goodsnumber=" + goodsnumber + ", goodspic=" + goodspic
				+ ", getGoodsid()=" + getGoodsid() + ", getGoodsname()="
				+ getGoodsname() + ", getGoodstype()=" + getGoodstype()
				+ ", getGoodsprice()=" + getGoodsprice()
				+ ", getGoodsnumber()=" + getGoodsnumber() + ", getGoodspic()="
				+ getGoodspic() + ", hashCode()=" + hashCode()
				+ ", getClass()=" + getClass() + ", toString()="
				+ super.toString() + "]";
	}

	public int getIscollect() {
		return iscollect;
	}

	public void setIscollect(int iscollect) {
		this.iscollect = iscollect;
	}

}
