package com.oracle.xianshop.model.javabean;

import java.io.Serializable;

/**
 * 订单�? 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Orders implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 订单编号. */
	private String orderid;
	
	private String name;
	/** 下单时间. */
	private String orderdate;

	/** 订单状�??. */
	private String orderstatus;

	/** 收货地址. */
	private String address;

	/** 备注. */
	private String remarks;

	/** 用户编号. */
	private Integer userid;

	/**
	 * 僐儞僗僩儔僋�?.
	 */
	public Orders() {
	}

	/**
	 * 订单编号 傪愝掕偟傑偡.
	 * 
	 * @param orderid
	 *            订单编号
	 */
	public void setOrderid(String orderid) {
		this.orderid = orderid;
	}

	/**
	 * 订单编号 傪庢摼偟傑偡.
	 * 
	 * @return 订单编号
	 */
	public String getOrderid() {
		return this.orderid;
	}

	/**
	 * 下单时间 傪愝掕偟傑偡.
	 * 
	 * @param orderdate
	 *            下单时间
	 */
	public void setOrderdate(String orderdate) {
		this.orderdate = orderdate;
	}

	/**
	 * 下单时间 傪庢摼偟傑偡.
	 * 
	 * @return 下单时间
	 */
	public String getOrderdate() {
		return this.orderdate;
	}

	/**
	 * 订单状�?? 傪愝掕偟傑偡.
	 * 
	 * @param orderstatus
	 *            订单状�??
	 */
	public void setOrderstatus(String orderstatus) {
		this.orderstatus = orderstatus;
	}

	/**
	 * 订单状�?? 傪庢摼偟傑偡.
	 * 
	 * @return 订单状�??
	 */
	public String getOrderstatus() {
		return this.orderstatus;
	}

	/**
	 * 收货地址 傪愝掕偟傑偡.
	 * 
	 * @param address
	 *            收货地址
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * 收货地址 傪庢摼偟傑偡.
	 * 
	 * @return 收货地址
	 */
	public String getAddress() {
		return this.address;
	}

	/**
	 * 备注 傪愝掕偟傑偡.
	 * 
	 * @param remarks
	 *            备注
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * 备注 傪庢摼偟傑偡.
	 * 
	 * @return 备注
	 */
	public String getRemarks() {
		return this.remarks;
	}

	/**
	 * 用户编号 傪愝掕偟傑偡.
	 * 
	 * @param userid
	 *            用户编号
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * 用户编号 傪庢摼偟傑偡.
	 * 
	 * @return 用户编号
	 */
	public Integer getUserid() {
		return this.userid;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((orderid == null) ? 0 : orderid.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Orders other = (Orders) obj;
		if (orderid == null) {
			if (other.orderid != null) {
				return false;
			}
		} else if (!orderid.equals(other.orderid)) {
			return false;
		}

		return true;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
